#!/usr/bin/env python3
"""Build the memorial site's display-sized images and en/zh-cn Moment bundle.

Only derivatives are written. Original artwork and vendored Moment are retained.
Requires Pillow with WebP support (also used by the project's asset tools).
"""

import argparse
import json
from pathlib import Path

from PIL import Image, ImageOps

ROOT = Path(__file__).resolve().parents[1]
SITE = ROOT / "site"
OUTPUT = SITE / "imgs" / "optimized"


def moment_bundle():
    source = (SITE / "js" / "moment-with-locales.js").read_text(encoding="utf-8")
    marker = "    //! moment.js locale configuration"
    core_end = source.index(marker)
    locale_start = source.index("    hooks.defineLocale('zh-cn', {")
    locale_end = source.index(marker, locale_start)
    footer = source.rindex("    hooks.locale('en');")
    if "hooks.version = '2.29.4';" not in source or not core_end < locale_start < locale_end < footer:
        raise ValueError("Moment source changed; review the locale extraction before rebuilding")
    return (
        "// Generated by tools/build_frontend_assets.py: Moment 2.29.4, en + zh-cn.\n"
        + source[:core_end]
        + source[locale_start:locale_end]
        + source[footer:]
    )


def image_sources():
    # The full-size JPEG is smaller than a quality-92 WebP; keep it on desktop.
    yield SITE / "imgs" / "op1900.jpg", (960,)
    yield SITE / "imgs" / "Kirara_part2_Star5_StandPic_0.png", (480,)
    official = SITE / "imgs" / "official-site"
    yield official / "official-original-cast.png", (800, 1646)
    for number in range(1, 5):
        yield official / "hero" / f"hero-{number:02d}-pc.png", (800, 1646)
    archive = SITE / "asset" / "shutdown-artworks"
    data = json.loads((archive / "artworks.js").read_text(encoding="utf-8").split("=", 1)[1].strip().rstrip(";"))
    for artwork in data["items"]:
        yield archive / artwork["images"][0]["path"], (640, 960)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Check generated files without writing")
    args = parser.parse_args()
    moment_path = SITE / "js" / "moment-zh-cn.js"
    moment = moment_bundle()
    if args.check:
        if not moment_path.exists() or moment_path.read_text(encoding="utf-8") != moment:
            raise SystemExit("Moment derivative is missing or out of date")
    else:
        moment_path.write_text(moment, encoding="utf-8", newline="\n")
        OUTPUT.mkdir(parents=True, exist_ok=True)

    original_bytes = 0
    largest_bytes = 0
    count = 0
    for source, widths in image_sources():
        original_bytes += source.stat().st_size
        with Image.open(source) as original:
            has_alpha = "A" in original.getbands() or "transparency" in original.info
            image = ImageOps.exif_transpose(original).convert("RGBA" if has_alpha else "RGB")
            profile = image.info.get("icc_profile") or b""
            for width in widths:
                target = OUTPUT / f"{source.stem}-{width}.webp"
                actual_width = min(width, image.width)
                size = (actual_width, round(image.height * actual_width / image.width))
                if args.check:
                    with Image.open(target) as derivative:
                        if derivative.size != size or derivative.format != "WEBP":
                            raise SystemExit(f"Unexpected derivative: {target}")
                        if has_alpha and image.getextrema()[-1][0] < 255 and "A" not in derivative.getbands():
                            raise SystemExit(f"Transparency was lost: {target}")
                        if (derivative.info.get("icc_profile") or b"") != profile:
                            raise SystemExit(f"Color profile changed: {target}")
                else:
                    resized = image.resize(size, Image.Resampling.LANCZOS)
                    resized.save(target, "WEBP", quality=92, method=6, icc_profile=profile)
                count += 1
            largest_bytes += target.stat().st_size

    print(json.dumps({
        "mode": "check" if args.check else "build",
        "moment_original_bytes": (SITE / "js" / "moment-with-locales.js").stat().st_size,
        "moment_derivative_bytes": len(moment.encode("utf-8")),
        "image_derivatives": count,
        "original_image_bytes": original_bytes,
        "largest_derivative_bytes": largest_bytes,
    }, indent=2))


if __name__ == "__main__":
    main()
