#!/usr/bin/env python3
"""Extract battle tables out of the game's own master database.

These tables are NOT available over HTTP -- every database.kirafan.cn
`*SkillList.json` endpoint 404s, because skill data ships inside the asset
bundle `database/database.muast` instead.  This reads that bundle directly.

Outputs (all under asset/battle/):
    skills.js         SkillList_PL, keyed by skill id
    uniqueskill.js    per-card totteoki: scene bundle, cue sheets, sound frames
    battledefine.js   BattleDefine params + TogetherChargeDefine

Usage:
    python tools/extract_battle_data.py [--db .codex-tmp/db/database.muast]
"""

import argparse
import io
import json
import os
import sys

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Tables we read.  Names are the MonoBehaviour m_Name inside database.muast.
WANTED = [
    "SkillList_PL",
    "SkillList_EN",
    "SkillList_WPN",
    "SkillList_MST",
    "SkillList_CARD",
    "UniqueSkillSound",
    "BattleDefine",
    "TogetherChargeDefine",
]


def read_tables(db_path, names):
    import UnityPy
    env = UnityPy.load(db_path)
    found = {}
    for obj in env.objects:
        if obj.type.name != "MonoBehaviour":
            continue
        try:
            data = obj.read()
        except Exception:
            continue
        name = getattr(data, "m_Name", "") or ""
        if name in names and name not in found:
            try:
                found[name] = obj.read_typetree()
            except Exception as exc:
                print("  ! %s: typetree failed (%s)" % (name, exc))
    return found


def write_js(path, varname, payload, note):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("// Generated by tools/extract_battle_data.py. Do not edit by hand.\n")
        fh.write("// %s\n" % note)
        fh.write("window.%s = " % varname)
        json.dump(payload, fh, ensure_ascii=False, separators=(",", ":"))
        fh.write(";\n")
    size = os.path.getsize(path)
    print("  wrote %s (%.1f KB)" % (os.path.relpath(path, ROOT), size / 1024.0))


def r3(v):
    """Floats in the tables are float32 widened to double; round off the noise."""
    if isinstance(v, float):
        return round(v, 4)
    if isinstance(v, list):
        return [r3(x) for x in v]
    return v


def collapse(values):
    """m_Recasts / m_LoadFactors are per-skill-level-band; most are all-equal."""
    vals = [r3(v) for v in values]
    if vals and all(v == vals[0] for v in vals):
        return vals[0]
    return vals


def build_skills(tables, out_dir):
    """SkillList_PL is the player-side skill table (2832 rows)."""
    tree = tables.get("SkillList_PL")
    if not tree:
        print("  ! SkillList_PL missing, skipping skills.js")
        return {}
    skills = {}
    for p in tree["m_Params"]:
        entry = {
            "name": p["m_SkillName"],
            "detail": p["m_SkillDetail"],
            "type": p["m_SkillType"],
            "sap": p["m_SAP"],
            "load": collapse(p["m_LoadFactors"]),
        }
        if p["m_SAG"] and p["m_SAG"] != "Empty":
            entry["sag"] = p["m_SAG"]
        recast = collapse(p["m_Recasts"])
        if recast:
            entry["recast"] = recast
        skills[str(p["m_ID"])] = entry
    write_js(os.path.join(out_dir, "skills.js"), "kirafanSkillData",
             {"meta": {"source": "database.muast SkillList_PL",
                       "count": len(skills)},
              "skills": skills},
             "Skill table. LoadFactor is the timeline cost multiplier.")
    return tree


def build_uniqueskill(tables, skill_tree, out_dir):
    """Join SkillList_PL's totteoki rows against UniqueSkillSound frame data."""
    sound = tables.get("UniqueSkillSound")
    if not skill_tree:
        print("  ! no skill table, skipping uniqueskill.js")
        return
    # cue sheet -> [[frame, cueId], ...]
    frames = {}
    if sound:
        for p in sound["m_Params"]:
            frames[p["m_CueSheet"]] = [[d["m_PlayFrame"], d["m_CueID"]]
                                       for d in p["m_Datas"]]

    entries = {}
    for p in skill_tree["m_Params"]:
        scene = p["m_UniqueSkillScene"]
        if not scene:
            continue
        se = p["m_UniqueSkillSeCueSheet"]
        voice = p["m_UniqueSkillVoiceCueSheet"]
        entry = {
            "skillId": p["m_ID"],
            "name": p["m_SkillName"],
            "detail": p["m_SkillDetail"],
            # scene "PL_100001_0" -> uniqueskill/uniqueskill_pl_100001_0
            "bundle": "uniqueskill/uniqueskill_%s" % scene.lower(),
            "load": collapse(p["m_LoadFactors"]),
        }
        if se:
            entry["se"] = {"sheet": se, "frames": frames.get(se, [])}
        if voice:
            # Voice cue ids are positional: voice_kirarajump_000, _001, ...
            # (UniqueSkillSoundDB_Ext rewrites them by index, ignoring m_CueID.)
            vf = frames.get(voice, [])
            entry["voice"] = {
                "sheet": voice,
                "frames": [[f, "voice_kirarajump_%03d" % i]
                           for i, (f, _) in enumerate(vf)]
            }
        if p["m_UniqueSkillBgmCueName"]:
            entry["bgm"] = p["m_UniqueSkillBgmCueName"]
        entries[scene] = entry

    write_js(os.path.join(out_dir, "uniqueskill.js"), "kirafanUniqueSkillData",
             {"meta": {"source": "database.muast SkillList_PL + UniqueSkillSound",
                       "count": len(entries),
                       "note": "Audio cues are CRIWARE names; the .acb/.awb "
                               "payloads are not served by the asset host."},
              "scenes": entries},
             "Totteoki presentation: bundle, frame-synced SE/voice cues.")


def build_define(tables, out_dir):
    payload = {"meta": {"source": "database.muast"}}
    bd = tables.get("BattleDefine")
    if bd:
        params = bd.get("m_Params") or []
        payload["battle"] = r3(params)
    tc = tables.get("TogetherChargeDefine")
    if tc:
        payload["togetherCharge"] = r3(tc.get("m_Params") or [])
    if len(payload) == 1:
        print("  ! no define tables found, skipping battledefine.js")
        return
    write_js(os.path.join(out_dir, "battledefine.js"), "kirafanBattleDefine",
             payload,
             "Raw param arrays. Index<->meaning drifts between versions; see "
             "docs and .codex-tmp/research-battle.md before trusting an index.")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--db", default=os.path.join(ROOT, ".codex-tmp", "db",
                                                 "database.muast"))
    ap.add_argument("--out", default=os.path.join(ROOT, "asset", "battle"))
    args = ap.parse_args()

    if not os.path.exists(args.db):
        print("missing database bundle: %s" % args.db)
        return 1

    print("reading %s" % os.path.relpath(args.db, ROOT))
    tables = read_tables(args.db, set(WANTED))
    print("found tables: %s" % ", ".join(sorted(tables)))
    missing = [n for n in WANTED if n not in tables]
    if missing:
        print("not present: %s" % ", ".join(missing))

    skill_tree = build_skills(tables, args.out)
    build_uniqueskill(tables, skill_tree, args.out)
    build_define(tables, args.out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
