"""Natural shop stock, failed writes, retry, duplicate effects and old-stock resumes.

Coin is a resource fixture. The original stock is generated by the actual room;
the separately labelled legacy save is an explicit compatibility fixture.
"""
import functools
import json
import threading
from pathlib import Path

from playwright.sync_api import sync_playwright
from serve import NoCacheHandler, Server
from rl_floor_loot_browser import ready, advance
from rl_recovery_browser import press
from rl_persistence_browser import inject_quota
from rl_feedback_experience_browser import acquire, STATE, fingerprints, readability

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / '.codex-tmp/feedback-20260910/gadget-acquisition'
PRICES = {'rhythm': 40, 'strider': 45, 'reach': 45, 'wide': 40, 'aim': 30, 'sentry': 90, 'hunter': 130,
          'steady': 120, 'prism': 160, 'binding': 180}


def profile(page):
    return page.evaluate("JSON.parse(localStorage.getItem('kirafan-rl:profile'))")


def enter_shop(page, coin=None):
    room_id = page.evaluate("""coin=>{const k=kirafanRL,w=k.world,r=w.dungeon.rooms.find(r=>r.type==='shop');
        if(!r)throw Error('自然地图缺少商店');w.enterRoom(r.id);if(coin!==null)w.coin=coin;k.step(1/60);return r.id;}""", coin)
    ready(page); press(page, 'KeyE'); page.wait_for_selector('#shop-panel[open]')
    return room_id


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    report = {'checks': [], 'errors': [], 'before': fingerprints()}

    def check(label, ok, detail=None):
        report['checks'].append({'label': label, 'ok': bool(ok), 'detail': detail})
        print(('PASS ' if ok else 'FAIL ') + label, flush=True)
        if not ok:
            raise AssertionError(label + ': ' + str(detail))

    server = Server(('127.0.0.1', 0), functools.partial(NoCacheHandler, directory=str(ROOT)))
    worker = threading.Thread(target=server.serve_forever, daemon=True); worker.start()
    page = None
    try:
        with sync_playwright() as pw:
            browser = pw.chromium.launch(args=['--use-gl=angle', '--enable-unsafe-swiftshader'])
            context = browser.new_context(viewport={'width': 1280, 'height': 840})
            context.add_init_script("""window.requestAnimationFrame=()=>0;window.cancelAnimationFrame=()=>{};
                if(!localStorage.getItem('kirafan-rl:profile'))localStorage.setItem('kirafan-rl:meta',
                    JSON.stringify({prologueSeen:true,tutorialSeen:true}));""")
            page = context.new_page(); page.on('pageerror', lambda e: report['errors'].append(str(e)))
            base = 'http://127.0.0.1:%d/site/game/roguelike.html' % server.server_address[1]
            page.goto(base + '?volume=1&floor=9&seed=260909', wait_until='load', timeout=60000)
            page.locator('.roster-card').filter(has=page.locator('img[src$="/32002001.webp"]')).click(timeout=60000)
            ready(page); shop_id = enter_shop(page, 300)
            stock = page.evaluate('kirafanRL.world.getShopOffer()'); report['naturalStock'] = stock
            gid = stock[2]['item']['gadgetId']; price = PRICES[gid]
            check('自然商店三货位分别是武器、词条装备和机制', len(stock) == 3
                  and stock[0]['item']['slot'] == 'weapon' and 'gadgetId' not in stock[0]['item']
                  and stock[1]['item']['slot'] != 'weapon' and 'gadgetId' not in stock[1]['item']
                  and stock[2]['price'] == price, stock)
            button = page.locator('#shop-items [data-index="2"]')
            check('货架展示对应机制图示及固定价格', button.locator('img').get_attribute('src').endswith('/gadget-' + gid + '.svg')
                  and (str(price) + ' 金币') in button.inner_text())
            before = page.evaluate(STATE); button.click()
            check('购买比较尚未扣费或改变装备', page.evaluate(STATE) == before)
            page.locator('#equipment-keep').click()
            check('取消比较不消耗货架', page.evaluate(STATE) == before)
            button.click(); durable = page.evaluate("localStorage.getItem('kirafan-rl:profile')")
            inject_quota(page); page.locator('#equipment-confirm').click()
            check('真实配额故障确实到达存储并拒绝整笔购买', page.evaluate('profileAttempts') > 0
                  and page.evaluate(STATE) == before and page.evaluate("localStorage.getItem('kirafan-rl:profile')") == durable)
            check('失败后窗口保留且允许重试，明确没有消耗', page.locator('#rl-equipment-choice').is_visible()
                  and page.locator('#equipment-confirm').is_enabled()
                  and '未消耗' in page.locator('#rl-equipment-choice .decision-status').inner_text())
            page.screenshot(path=str(OUT / 'purchase-failed.png'))
            page.locator('#equipment-keep').click(); page.locator('#shop-close').click()
            page.evaluate('window.blockWrites=false'); page.locator('#save-status-retry').click()
            check('取消后修复存储不会偷偷执行旧购买', page.evaluate(STATE) == before
                  and profile(page)['run']['coin'] == 300
                  and not next(row for row in profile(page)['run']['roomClaims'] if row['id'] == shop_id)['offer'][2]['bought'])
            press(page, 'KeyE'); button.click()
            page.evaluate('window.blockWrites=true'); page.locator('#equipment-confirm').click()
            check('再次失败也不改变金币、装配或已售标记', page.evaluate(STATE) == before)
            page.evaluate('window.blockWrites=false'); page.locator('#equipment-confirm').click(); advance(page)
            purchased = profile(page)['run']; live = page.evaluate('kirafanRL.world.player.equipment')
            claim = next(row for row in purchased['roomClaims'] if row['id'] == shop_id)
            check('重试成功后金币、装备和已售标记一起落盘', purchased['coin'] == 300 - price
                  and purchased['equipment'] == live and any(i.get('gadgetId') == gid for i in live)
                  and claim['offer'][2]['bought'])
            check('成功后同一货位禁用，不依赖客户端重复点击防抖', button.is_disabled()
                  and page.evaluate('kirafanRL.buyShopItem(2)===null'))
            after = page.evaluate(STATE); advance(page, .1)
            check('后续帧不重复扣费', page.evaluate(STATE) == after)
            page.screenshot(path=str(OUT / 'purchase-saved.png'))
            page.locator('#shop-close').click(); page.reload(wait_until='load')
            page.locator('#roster-continue').click(timeout=60000); ready(page); enter_shop(page)
            check('刷新续档保留完整库存、原价格与已售状态', page.evaluate('kirafanRL.world.getShopOffer()') == claim['offer']
                  and page.evaluate('kirafanRL.world.coin') == purchased['coin'])
            check('续档不静默启动自动战斗', not page.evaluate('kirafanRL.world.assistance.enabled'))

            # A genuine saved envelope, with explicitly authored older rarity/price.
            legacy = profile(page)
            saved_claim = next(row for row in legacy['run']['roomClaims'] if row['id'] == shop_id)
            old_item = {**stock[2]['item'], 'rarity': 'legendary'}
            saved_claim['offer'][2] = {'item': old_item, 'price': 17, 'bought': False}
            legacy['run']['equipment'] = [{**old_item, 'rarity': 'common'}]
            legacy['run']['coin'] = 100
            (OUT / 'legacy-fixture.json').write_text(json.dumps(legacy, ensure_ascii=False, indent=2), encoding='utf8')
            context.close()
            context = browser.new_context(viewport={'width': 1280, 'height': 840})
            context.add_init_script("window.requestAnimationFrame=()=>0;window.cancelAnimationFrame=()=>{};"
                + "if(!localStorage.getItem('kirafan-rl:profile'))localStorage.setItem('kirafan-rl:profile',"
                + json.dumps(json.dumps(legacy, ensure_ascii=False)) + ');')
            page = context.new_page(); page.on('pageerror', lambda e: report['errors'].append(str(e)))
            page.goto(base, wait_until='load', timeout=60000)
            page.locator('#roster-continue').click(timeout=60000); ready(page); enter_shop(page)
            loaded = page.evaluate('kirafanRL.world.getShopOffer()[2]')
            check('旧档低价和不同品质原样恢复，不重抽或涨价', loaded == saved_claim['offer'][2], loaded)
            button = page.locator('#shop-items [data-index="2"]')
            before = page.evaluate(STATE)
            check('相同机制的不同旧品质在货架明确禁购', button.is_disabled() and '同一机制' in button.inner_text()
                  and page.evaluate('kirafanRL.buyShopItem(2)===null') and page.evaluate(STATE) == before)
            check('旧传说包装不再显示成更强的机制', '传说' not in button.inner_text())
            contrasts = readability(page, '#shop-items [data-index="2"] .item-name, #shop-items [data-index="2"] .item-price, #shop-items [data-index="2"] .gadget-cost')
            check('禁购仍可读具体名称、原因和代价，不靠整体半透明', contrasts
                  and all(row['ratio'] >= 4.5 for row in contrasts), contrasts)
            page.screenshot(path=str(OUT / 'same-effect-blocked.png'))
            page.locator('#shop-close').click()
            alternative = page.evaluate("""async item=>{const {GADGETS,makeGadget}=await import('/site/game/rl/gadgets.js');
                return makeGadget(GADGETS.find(g=>g.slot===item.slot&&g.id!==item.gadgetId).id);}""", old_item)
            acquire(page, alternative); press(page, 'KeyE')
            check('正常换成另一机制后可按原价重新购买', button.is_enabled() and '17 金币' in button.inner_text())
            button.click(); page.locator('#equipment-confirm').click(); advance(page)
            check('旧货架的合法替换只扣原价一次', page.evaluate('kirafanRL.world.coin') == 83
                  and profile(page)['run']['coin'] == 83
                  and old_item in page.evaluate('kirafanRL.world.player.equipment'))
            check('没有未捕获页面错误', not report['errors'], report['errors'])
            report['after'] = fingerprints(); check('验证期间产品源文件未变', report['before'] == report['after'])
            context.close(); browser.close()
    finally:
        server.shutdown(); worker.join(timeout=5)
        report['after'] = fingerprints()
        (OUT / 'report.json').write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding='utf8')


if __name__ == '__main__':
    main()
